#!/usr/bin/env python3
import vitis
import os
import shutil
import re
import time
from datetime import datetime
import platform as os_platform

# This script is auto-generated by Vitis IDE

vitis.dispose()

print("\n---------------------------------------------------------")
print("  Migrating classic Vitis projects to Vitis Unified IDE  ")
print("---------------------------------------------------------")

# Create Vitis client
client = vitis.create_client()

print('getcwd:      ', os.getcwd())
print('__file__:    ', __file__)

date = datetime.now().strftime("%Y%m%d%I%M%S")

script_path = os.path.dirname(os.path.abspath(__file__))

if(os_platform.system() == "Windows"):
   ws_path = script_path+'\\ws_'+date+'\\'
else:
   ws_path = script_path+'/ws_'+date+'/'
#Delete the workspace if already exists.
if (os.path.isdir(ws_path)):
    shutil.rmtree(ws_path)
    print(f"Deleted workspace {ws_path}")

client.set_workspace(ws_path)
print('Successfully created Vitis client on workspace {}'.format(client.get_workspace()))

print('getcwd:      ', os.getcwd())
print('__file__:    ', __file__)

print("Migrating projects from classic Vitis IDE")

app_names = []

for dirpath, dirnames, filenames in os.walk(script_path + '/src'):
    #print(dirpath)
#    print(dirnames)
    print(filenames)
    
    for dirname in dirnames:
        if re.search(r'src', dirname):
            print(dirpath)
            application_name = os.path.basename(dirpath)
            print(application_name)
            print(f'this is the name of the project: {application_name}')
            app_names.append(application_name)
            print(app_names)
    
    match = re.search(r'src\.+', dirpath)
    print(match)
    #if re.search(f"src\.+", dirpath):
    for filename in filenames:
        if filename.endswith(".xsa"):
            file = os.path.join(dirpath, filename)
            print(f'Found - {file}')
            print(f'xsa dirpath = {dirpath}')
            print(f'xsa dirname = {os.path.basename(dirpath)}')
            xsa_dirpath_name = os.path.basename(dirpath)
        else:
            print("it doesn't work")

print(f'\nDetected one or more applications present: {app_names}')
mcu = client.get_processor_os_list(xsa = file)
print(f"\nProcessor device family is: {mcu.deviceFamily}")


if(mcu.deviceFamily == 'fpga'):
    # Migrating platform project : 'D:\zybo_vitis_unified_hdmi\ws\design_1_wrapper\platform.spr'
    print("Creating platform component " + xsa_dirpath_name + '.')
    platform = client.create_platform_component(name = xsa_dirpath_name, hw_design = file, no_boot_bsp = True)
    platform.update_desc(desc = xsa_dirpath_name)
    print("Adding new domain 'domain_microblaze_0' for cpu: 'microblaze_0' and OS: 'standalone'")
    domain = platform.add_domain(cpu = 'microblaze_0', os = 'standalone', name = 'domain_microblaze_0', display_name = 'domain_microblaze_0')
    print("Configuring the domain 'domain_microblaze_0'...")
    print("Migrating BSP settings for the domain 'domain_microblaze_0'")
    # Setting config params for processor
    try:
        domain.set_config(option = 'proc', param = 'proc_extra_compiler_flags', value = '-g -ffunction-sections -fdata-sections -Wall -Wextra')
    except:
        print('ERROR: Failed to set config param proc_extra_compiler_flags for processor')
    try:
        domain.set_config(option = 'proc', param = 'proc_xmdstub_peripheral', value = 'none')
    except:
        print('ERROR: Failed to set config param proc_xmdstub_peripheral for processor')
    try:
        domain.set_config(option = 'proc', param = 'proc_archiver', value = 'mb-ar')
    except:
        print('ERROR: Failed to set config param proc_archiver for processor')
    try:
        domain.set_config(option = 'proc', param = 'proc_dependency_flags', value = '-MMD -MP')
    except:
        print('ERROR: Failed to set config param proc_dependency_flags for processor')
    try:
        domain.set_config(option = 'proc', param = 'proc_assembler', value = 'mb-as')
    except:
        print('ERROR: Failed to set config param proc_assembler for processor')
    try:
        domain.set_config(option = 'proc', param = 'proc_compiler_flags', value = '-O2 -c')
    except:
        print('ERROR: Failed to set config param proc_compiler_flags for processor')
    try:
        domain.set_config(option = 'proc', param = 'proc_compiler', value = 'mb-gcc')
    except:
        print('ERROR: Failed to set config param proc_compiler for processor')

    # Setting config params for OS standalone
    try:
        domain.set_config(option = 'os', param = 'standalone_microblaze_exceptions', value = 'false')
    except:
        print('ERROR: Failed to set config param standalone_microblaze_exceptions for OS standalone')
    try:
        domain.set_config(option = 'os', param = 'standalone_stdin', value = 'axi_uartlite_0')
    except:
        print('ERROR: Failed to set config param standalone_stdin for OS standalone')
    try:
        domain.set_config(option = 'os', param = 'standalone_ttc_select_cntr', value = '2')
    except:
        print('ERROR: Failed to set config param standalone_ttc_select_cntr for OS standalone')
    try:
        domain.set_config(option = 'os', param = 'standalone_stdout', value = 'axi_uartlite_0')
    except:
        print('ERROR: Failed to set config param standalone_stdout for OS standalone')
    try:
        domain.set_config(option = 'os', param = 'standalone_predecode_fpu_exceptions', value = 'false')
    except:
        print('ERROR: Failed to set config param standalone_predecode_fpu_exceptions for OS standalone')
    try:
        domain.set_config(option = 'os', param = 'standalone_sleep_timer', value = 'none')
    except:
        print('ERROR: Failed to set config param standalone_sleep_timer for OS standalone')
    try:
        domain.set_config(option = 'os', param = 'standalone_enable_sw_intrusive_profiling', value = 'false')
    except:
        print('ERROR: Failed to set config param standalone_enable_sw_intrusive_profiling for OS standalone')
    try:
        domain.set_config(option = 'os', param = 'standalone_hypervisor_guest', value = 'false')
    except:
        print('ERROR: Failed to set config param standalone_hypervisor_guest for OS standalone')
    try:
        domain.set_config(option = 'os', param = 'standalone_clocking', value = 'false')
    except:
        print('ERROR: Failed to set config param standalone_clocking for OS standalone')
    try:
        domain.set_config(option = 'os', param = 'standalone_zynqmp_fsbl_bsp', value = 'false')
    except:
        print('ERROR: Failed to set config param standalone_zynqmp_fsbl_bsp for OS standalone')
    try:
        domain.set_config(option = 'os', param = 'standalone_lockstep_mode_debug', value = 'false')
    except:
        print('ERROR: Failed to set config param standalone_lockstep_mode_debug for OS standalone')
    try:
        domain.set_config(option = 'os', param = 'standalone_profile_timer', value = 'none')
    except:
        print('ERROR: Failed to set config param standalone_profile_timer for OS standalone')
else:
    # Migrating platform project : 'D:\zybo_vitis_unified_hdmi\ws\design_1_wrapper\platform.spr'
    print("Creating platform component " + xsa_dirpath_name + '.')
    platform = client.create_platform_component(name = xsa_dirpath_name, hw_design = file)
    platform.update_desc(desc = xsa_dirpath_name)
    print("Adding new domain 'domain_ps7_cortexa9_0' for cpu: 'ps7_cortexa9_0' and OS: 'standalone'")
    domain = platform.add_domain(cpu = 'ps7_cortexa9_0', os = 'standalone', name = 'domain_ps7_cortexa9_0', display_name = 'domain_ps7_cortexa9_0')
    print("Configuring the domain 'domain_ps7_cortexa9_0'...")
    print("Migrating BSP settings for the domain 'domain_ps7_cortexa9_0'")

platform.build()

print('\n')
for driver in domain.get_drivers():
    print(driver['name'])

for app_name in app_names:
    # Migrating application project
    print(f'Creating application component {app_name}')
    app = client.create_app_component(name = app_name, platform = client.get_workspace() + '/' + xsa_dirpath_name + '/' + 'export' + '/' + xsa_dirpath_name + '/' + xsa_dirpath_name + '.xpfm', domain = 'domain_ps7_cortexa9_0', template = 'hello_world')
    app.set_app_config(key='USER_COMPILE_DEFINITIONS', values=['DEBUG'])
    app.set_app_config(key='USER_COMPILE_DEBUG_LEVEL', values=['-g3'])
    app.set_app_config(key='USER_LINK_LIBRARIES', values=['m'])
    if(mcu.deviceFamily == 'zynq'):
        app.set_app_config(key='USER_COMPILE_OTHER_FLAGS', values='"-fmessage-length=0 -MT"$$@" -mcpu=cortex-a9 -mfpu=vfpv3 -mfloat-abi=hard"')
        app.set_app_config(key='USER_LINK_OTHER_FLAGS', values='"-mcpu=cortex-a9 -mfpu=vfpv3 -mfloat-abi=hard -Wl,-build-id=none"')

    app.import_files(from_loc = script_path + '/src/' + app.component_name + '/src/', dest_dir_in_cmp = "src")
    print(f'\nApp component location: {app.component_location}\n')
    #Removing files generated by the hello_world template
    for dirpath, dirnames, filenames in os.walk(app.component_location + '/src/'):
        print(filenames)
        for filename in filenames:
            if filename == 'helloworld.c' or filename == 'Xilinx.spec' or filename == 'README.txt':
                print(f'\nRemoving {filename} from {os.path.join(dirpath, filename)}')
                app.remove_files(files = [app.component_location + '/src/' + filename] )
    #app.remove_files(files = [app.component_location + '/src/helloworld.c', app.component_location + '/src/Xilinx.spec'] )
    #app.remove_files(files = [app.component_location + '/src/Xilinx.spec'] )
    
    #Removing tcl files that should not be there
    for dirpath, dirnames, filenames in os.walk(app.component_location + '/_ide/psinit/'):
        print('\n')
        print(filenames)
        for filename in filenames:
            if filename != 'ps7_init.tcl':
                print(f'\nRemoving {filename} from {os.path.join(dirpath, filename)}')
                app.remove_files(files = [app.component_location + '/_ide/psinit/' + filename] )

    app.build()

vitis.dispose()
